FROM otaciliopsf/spark-py:v3.1.1-hadoop3.2-abfss-delta

USER root:root

WORKDIR /opt/spark/work-dir

COPY jars/postgresql-42.3.1.jar /opt/spark/jars/postgresql-42.3.1.jar
RUN pip install requests

COPY insgestion-spark-job.py insgestion-spark-job.py

ENTRYPOINT [ "/opt/spark/bin/spark-submit", "insgestion-spark-job.py" ]