version: '3.5'
services:

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: ny_taxi 
    volumes:
       - postgres-v:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pg-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin-v:/var/lib/pgadmin

    ports:
      - "8080:80"
    networks:
      - pg-network
    restart: unless-stopped

networks:
  pg-network:
    driver: bridge

volumes:
    postgres-v:
    pgadmin-v: