FROM python:3.9.10

RUN apt-get install wget

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY insgestion-python-job.py insgestion-python-job.py

ENTRYPOINT [ "python", "insgestion-python-job.py" ]